// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(mqtee_coreFFI)
import mqtee_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_mqtee_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_mqtee_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol MqttClientProtocol : AnyObject {
    
    func connect() throws 
    
    func disconnect() throws 
    
    func isConnected()  -> Bool
    
    func publish(topic: String, payload: Data, qos: QosLevel, retain: Bool, contentType: String?, responseTopic: String?, correlationData: Data?, messageExpiryInterval: UInt32?, payloadFormatIndicator: UInt8?, userProperties: [UserProperty]) throws 
    
    func subscribe(subscriptions: [SubscriptionRequest]) throws 
    
    func unsubscribe(topics: [String]) throws 
    
}

open class MqttClient:
    MqttClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_mqtee_core_fn_clone_mqttclient(self.pointer, $0) }
    }
public convenience init(config: ConnectionConfig, handler: MqttEventHandler)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeMqttError.lift) {
    uniffi_mqtee_core_fn_constructor_mqttclient_new(
        FfiConverterTypeConnectionConfig.lower(config),
        FfiConverterCallbackInterfaceMqttEventHandler.lower(handler),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_mqtee_core_fn_free_mqttclient(pointer, $0) }
    }

    

    
open func connect()throws  {try rustCallWithError(FfiConverterTypeMqttError.lift) {
    uniffi_mqtee_core_fn_method_mqttclient_connect(self.uniffiClonePointer(),$0
    )
}
}
    
open func disconnect()throws  {try rustCallWithError(FfiConverterTypeMqttError.lift) {
    uniffi_mqtee_core_fn_method_mqttclient_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_mqtee_core_fn_method_mqttclient_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
open func publish(topic: String, payload: Data, qos: QosLevel, retain: Bool, contentType: String?, responseTopic: String?, correlationData: Data?, messageExpiryInterval: UInt32?, payloadFormatIndicator: UInt8?, userProperties: [UserProperty])throws  {try rustCallWithError(FfiConverterTypeMqttError.lift) {
    uniffi_mqtee_core_fn_method_mqttclient_publish(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),
        FfiConverterData.lower(payload),
        FfiConverterTypeQosLevel.lower(qos),
        FfiConverterBool.lower(retain),
        FfiConverterOptionString.lower(contentType),
        FfiConverterOptionString.lower(responseTopic),
        FfiConverterOptionData.lower(correlationData),
        FfiConverterOptionUInt32.lower(messageExpiryInterval),
        FfiConverterOptionUInt8.lower(payloadFormatIndicator),
        FfiConverterSequenceTypeUserProperty.lower(userProperties),$0
    )
}
}
    
open func subscribe(subscriptions: [SubscriptionRequest])throws  {try rustCallWithError(FfiConverterTypeMqttError.lift) {
    uniffi_mqtee_core_fn_method_mqttclient_subscribe(self.uniffiClonePointer(),
        FfiConverterSequenceTypeSubscriptionRequest.lower(subscriptions),$0
    )
}
}
    
open func unsubscribe(topics: [String])throws  {try rustCallWithError(FfiConverterTypeMqttError.lift) {
    uniffi_mqtee_core_fn_method_mqttclient_unsubscribe(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(topics),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MqttClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MqttClient {
        return MqttClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MqttClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MqttClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> MqttClient {
    return try FfiConverterTypeMqttClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttClient_lower(_ value: MqttClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMqttClient.lower(value)
}


public struct ConnectionConfig {
    public var clientId: String
    public var host: String
    public var port: UInt16
    public var mqttVersion: MqttVersion
    public var cleanSession: Bool
    public var keepAliveSecs: UInt16
    public var username: String?
    public var password: String?
    public var useTls: Bool
    public var allowInsecureTls: Bool
    public var caCertificate: Data?
    public var clientCertificate: Data?
    public var clientKey: Data?
    public var lastWill: LastWillConfig?
    public var sessionExpiryInterval: UInt32?
    public var maxPacketSize: UInt32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(clientId: String, host: String, port: UInt16, mqttVersion: MqttVersion, cleanSession: Bool, keepAliveSecs: UInt16, username: String?, password: String?, useTls: Bool, allowInsecureTls: Bool, caCertificate: Data?, clientCertificate: Data?, clientKey: Data?, lastWill: LastWillConfig?, sessionExpiryInterval: UInt32?, maxPacketSize: UInt32?) {
        self.clientId = clientId
        self.host = host
        self.port = port
        self.mqttVersion = mqttVersion
        self.cleanSession = cleanSession
        self.keepAliveSecs = keepAliveSecs
        self.username = username
        self.password = password
        self.useTls = useTls
        self.allowInsecureTls = allowInsecureTls
        self.caCertificate = caCertificate
        self.clientCertificate = clientCertificate
        self.clientKey = clientKey
        self.lastWill = lastWill
        self.sessionExpiryInterval = sessionExpiryInterval
        self.maxPacketSize = maxPacketSize
    }
}



extension ConnectionConfig: Equatable, Hashable {
    public static func ==(lhs: ConnectionConfig, rhs: ConnectionConfig) -> Bool {
        if lhs.clientId != rhs.clientId {
            return false
        }
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.mqttVersion != rhs.mqttVersion {
            return false
        }
        if lhs.cleanSession != rhs.cleanSession {
            return false
        }
        if lhs.keepAliveSecs != rhs.keepAliveSecs {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.password != rhs.password {
            return false
        }
        if lhs.useTls != rhs.useTls {
            return false
        }
        if lhs.allowInsecureTls != rhs.allowInsecureTls {
            return false
        }
        if lhs.caCertificate != rhs.caCertificate {
            return false
        }
        if lhs.clientCertificate != rhs.clientCertificate {
            return false
        }
        if lhs.clientKey != rhs.clientKey {
            return false
        }
        if lhs.lastWill != rhs.lastWill {
            return false
        }
        if lhs.sessionExpiryInterval != rhs.sessionExpiryInterval {
            return false
        }
        if lhs.maxPacketSize != rhs.maxPacketSize {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(clientId)
        hasher.combine(host)
        hasher.combine(port)
        hasher.combine(mqttVersion)
        hasher.combine(cleanSession)
        hasher.combine(keepAliveSecs)
        hasher.combine(username)
        hasher.combine(password)
        hasher.combine(useTls)
        hasher.combine(allowInsecureTls)
        hasher.combine(caCertificate)
        hasher.combine(clientCertificate)
        hasher.combine(clientKey)
        hasher.combine(lastWill)
        hasher.combine(sessionExpiryInterval)
        hasher.combine(maxPacketSize)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionConfig {
        return
            try ConnectionConfig(
                clientId: FfiConverterString.read(from: &buf), 
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                mqttVersion: FfiConverterTypeMqttVersion.read(from: &buf), 
                cleanSession: FfiConverterBool.read(from: &buf), 
                keepAliveSecs: FfiConverterUInt16.read(from: &buf), 
                username: FfiConverterOptionString.read(from: &buf), 
                password: FfiConverterOptionString.read(from: &buf), 
                useTls: FfiConverterBool.read(from: &buf), 
                allowInsecureTls: FfiConverterBool.read(from: &buf), 
                caCertificate: FfiConverterOptionData.read(from: &buf), 
                clientCertificate: FfiConverterOptionData.read(from: &buf), 
                clientKey: FfiConverterOptionData.read(from: &buf), 
                lastWill: FfiConverterOptionTypeLastWillConfig.read(from: &buf), 
                sessionExpiryInterval: FfiConverterOptionUInt32.read(from: &buf), 
                maxPacketSize: FfiConverterOptionUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.clientId, into: &buf)
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterTypeMqttVersion.write(value.mqttVersion, into: &buf)
        FfiConverterBool.write(value.cleanSession, into: &buf)
        FfiConverterUInt16.write(value.keepAliveSecs, into: &buf)
        FfiConverterOptionString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.password, into: &buf)
        FfiConverterBool.write(value.useTls, into: &buf)
        FfiConverterBool.write(value.allowInsecureTls, into: &buf)
        FfiConverterOptionData.write(value.caCertificate, into: &buf)
        FfiConverterOptionData.write(value.clientCertificate, into: &buf)
        FfiConverterOptionData.write(value.clientKey, into: &buf)
        FfiConverterOptionTypeLastWillConfig.write(value.lastWill, into: &buf)
        FfiConverterOptionUInt32.write(value.sessionExpiryInterval, into: &buf)
        FfiConverterOptionUInt32.write(value.maxPacketSize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionConfig_lift(_ buf: RustBuffer) throws -> ConnectionConfig {
    return try FfiConverterTypeConnectionConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionConfig_lower(_ value: ConnectionConfig) -> RustBuffer {
    return FfiConverterTypeConnectionConfig.lower(value)
}


public struct LastWillConfig {
    public var topic: String
    public var message: String
    public var qos: QosLevel
    public var retain: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(topic: String, message: String, qos: QosLevel, retain: Bool) {
        self.topic = topic
        self.message = message
        self.qos = qos
        self.retain = retain
    }
}



extension LastWillConfig: Equatable, Hashable {
    public static func ==(lhs: LastWillConfig, rhs: LastWillConfig) -> Bool {
        if lhs.topic != rhs.topic {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        if lhs.qos != rhs.qos {
            return false
        }
        if lhs.retain != rhs.retain {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(topic)
        hasher.combine(message)
        hasher.combine(qos)
        hasher.combine(retain)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLastWillConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LastWillConfig {
        return
            try LastWillConfig(
                topic: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf), 
                qos: FfiConverterTypeQosLevel.read(from: &buf), 
                retain: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: LastWillConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.topic, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
        FfiConverterTypeQosLevel.write(value.qos, into: &buf)
        FfiConverterBool.write(value.retain, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLastWillConfig_lift(_ buf: RustBuffer) throws -> LastWillConfig {
    return try FfiConverterTypeLastWillConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLastWillConfig_lower(_ value: LastWillConfig) -> RustBuffer {
    return FfiConverterTypeLastWillConfig.lower(value)
}


public struct MqttMessage {
    public var topic: String
    public var payload: Data
    public var qos: QosLevel
    public var retain: Bool
    public var timestampMs: UInt64
    public var contentType: String?
    public var responseTopic: String?
    public var correlationData: Data?
    public var userProperties: [UserProperty]
    public var payloadFormatIndicator: UInt8?
    public var messageExpiryInterval: UInt32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(topic: String, payload: Data, qos: QosLevel, retain: Bool, timestampMs: UInt64, contentType: String?, responseTopic: String?, correlationData: Data?, userProperties: [UserProperty], payloadFormatIndicator: UInt8?, messageExpiryInterval: UInt32?) {
        self.topic = topic
        self.payload = payload
        self.qos = qos
        self.retain = retain
        self.timestampMs = timestampMs
        self.contentType = contentType
        self.responseTopic = responseTopic
        self.correlationData = correlationData
        self.userProperties = userProperties
        self.payloadFormatIndicator = payloadFormatIndicator
        self.messageExpiryInterval = messageExpiryInterval
    }
}



extension MqttMessage: Equatable, Hashable {
    public static func ==(lhs: MqttMessage, rhs: MqttMessage) -> Bool {
        if lhs.topic != rhs.topic {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        if lhs.qos != rhs.qos {
            return false
        }
        if lhs.retain != rhs.retain {
            return false
        }
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        if lhs.contentType != rhs.contentType {
            return false
        }
        if lhs.responseTopic != rhs.responseTopic {
            return false
        }
        if lhs.correlationData != rhs.correlationData {
            return false
        }
        if lhs.userProperties != rhs.userProperties {
            return false
        }
        if lhs.payloadFormatIndicator != rhs.payloadFormatIndicator {
            return false
        }
        if lhs.messageExpiryInterval != rhs.messageExpiryInterval {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(topic)
        hasher.combine(payload)
        hasher.combine(qos)
        hasher.combine(retain)
        hasher.combine(timestampMs)
        hasher.combine(contentType)
        hasher.combine(responseTopic)
        hasher.combine(correlationData)
        hasher.combine(userProperties)
        hasher.combine(payloadFormatIndicator)
        hasher.combine(messageExpiryInterval)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttMessage {
        return
            try MqttMessage(
                topic: FfiConverterString.read(from: &buf), 
                payload: FfiConverterData.read(from: &buf), 
                qos: FfiConverterTypeQosLevel.read(from: &buf), 
                retain: FfiConverterBool.read(from: &buf), 
                timestampMs: FfiConverterUInt64.read(from: &buf), 
                contentType: FfiConverterOptionString.read(from: &buf), 
                responseTopic: FfiConverterOptionString.read(from: &buf), 
                correlationData: FfiConverterOptionData.read(from: &buf), 
                userProperties: FfiConverterSequenceTypeUserProperty.read(from: &buf), 
                payloadFormatIndicator: FfiConverterOptionUInt8.read(from: &buf), 
                messageExpiryInterval: FfiConverterOptionUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: MqttMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.topic, into: &buf)
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterTypeQosLevel.write(value.qos, into: &buf)
        FfiConverterBool.write(value.retain, into: &buf)
        FfiConverterUInt64.write(value.timestampMs, into: &buf)
        FfiConverterOptionString.write(value.contentType, into: &buf)
        FfiConverterOptionString.write(value.responseTopic, into: &buf)
        FfiConverterOptionData.write(value.correlationData, into: &buf)
        FfiConverterSequenceTypeUserProperty.write(value.userProperties, into: &buf)
        FfiConverterOptionUInt8.write(value.payloadFormatIndicator, into: &buf)
        FfiConverterOptionUInt32.write(value.messageExpiryInterval, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttMessage_lift(_ buf: RustBuffer) throws -> MqttMessage {
    return try FfiConverterTypeMqttMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttMessage_lower(_ value: MqttMessage) -> RustBuffer {
    return FfiConverterTypeMqttMessage.lower(value)
}


public struct SubscriptionRequest {
    public var topic: String
    public var qos: QosLevel
    public var noLocal: Bool
    public var retainAsPublished: Bool
    public var retainHandling: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(topic: String, qos: QosLevel, noLocal: Bool, retainAsPublished: Bool, retainHandling: UInt8) {
        self.topic = topic
        self.qos = qos
        self.noLocal = noLocal
        self.retainAsPublished = retainAsPublished
        self.retainHandling = retainHandling
    }
}



extension SubscriptionRequest: Equatable, Hashable {
    public static func ==(lhs: SubscriptionRequest, rhs: SubscriptionRequest) -> Bool {
        if lhs.topic != rhs.topic {
            return false
        }
        if lhs.qos != rhs.qos {
            return false
        }
        if lhs.noLocal != rhs.noLocal {
            return false
        }
        if lhs.retainAsPublished != rhs.retainAsPublished {
            return false
        }
        if lhs.retainHandling != rhs.retainHandling {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(topic)
        hasher.combine(qos)
        hasher.combine(noLocal)
        hasher.combine(retainAsPublished)
        hasher.combine(retainHandling)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSubscriptionRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SubscriptionRequest {
        return
            try SubscriptionRequest(
                topic: FfiConverterString.read(from: &buf), 
                qos: FfiConverterTypeQosLevel.read(from: &buf), 
                noLocal: FfiConverterBool.read(from: &buf), 
                retainAsPublished: FfiConverterBool.read(from: &buf), 
                retainHandling: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: SubscriptionRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.topic, into: &buf)
        FfiConverterTypeQosLevel.write(value.qos, into: &buf)
        FfiConverterBool.write(value.noLocal, into: &buf)
        FfiConverterBool.write(value.retainAsPublished, into: &buf)
        FfiConverterUInt8.write(value.retainHandling, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSubscriptionRequest_lift(_ buf: RustBuffer) throws -> SubscriptionRequest {
    return try FfiConverterTypeSubscriptionRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSubscriptionRequest_lower(_ value: SubscriptionRequest) -> RustBuffer {
    return FfiConverterTypeSubscriptionRequest.lower(value)
}


public struct UserProperty {
    public var key: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }
}



extension UserProperty: Equatable, Hashable {
    public static func ==(lhs: UserProperty, rhs: UserProperty) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserProperty: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserProperty {
        return
            try UserProperty(
                key: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: UserProperty, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserProperty_lift(_ buf: RustBuffer) throws -> UserProperty {
    return try FfiConverterTypeUserProperty.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserProperty_lower(_ value: UserProperty) -> RustBuffer {
    return FfiConverterTypeUserProperty.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ConnectionEvent {
    
    case connected
    case disconnected(reason: String, reasonCode: String?
    )
    case messageReceived(message: MqttMessage
    )
    case publishAck(packetId: UInt16
    )
    case error(error: String
    )
    case subscribeAck(packetId: UInt16, returnCodes: String, reasonCodesDetail: String?
    )
    case unsubscribeAck(packetId: UInt16
    )
    case connAckDetails(sessionPresent: Bool, returnCode: String, reasonString: String?, assignedClientId: String?, serverKeepAlive: UInt16?, maximumQos: UInt8?, retainAvailable: Bool?, wildcardSubscriptionAvailable: Bool?, subscriptionIdentifiersAvailable: Bool?, sharedSubscriptionAvailable: Bool?, maximumPacketSize: UInt32?
    )
    case pubRecReceived(packetId: UInt16
    )
    case pubRelReceived(packetId: UInt16
    )
    case pubCompReceived(packetId: UInt16
    )
    case pingResponseReceived
    case publishSent(packetId: UInt16
    )
    case subscribeSent(packetId: UInt16
    )
    case unsubscribeSent(packetId: UInt16
    )
    case publishAckSent(packetId: UInt16
    )
    case pubRecSent(packetId: UInt16
    )
    case pubCompSent(packetId: UInt16
    )
    case pingSent
    case disconnectSent
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionEvent: FfiConverterRustBuffer {
    typealias SwiftType = ConnectionEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connected
        
        case 2: return .disconnected(reason: try FfiConverterString.read(from: &buf), reasonCode: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 3: return .messageReceived(message: try FfiConverterTypeMqttMessage.read(from: &buf)
        )
        
        case 4: return .publishAck(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 5: return .error(error: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .subscribeAck(packetId: try FfiConverterUInt16.read(from: &buf), returnCodes: try FfiConverterString.read(from: &buf), reasonCodesDetail: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 7: return .unsubscribeAck(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 8: return .connAckDetails(sessionPresent: try FfiConverterBool.read(from: &buf), returnCode: try FfiConverterString.read(from: &buf), reasonString: try FfiConverterOptionString.read(from: &buf), assignedClientId: try FfiConverterOptionString.read(from: &buf), serverKeepAlive: try FfiConverterOptionUInt16.read(from: &buf), maximumQos: try FfiConverterOptionUInt8.read(from: &buf), retainAvailable: try FfiConverterOptionBool.read(from: &buf), wildcardSubscriptionAvailable: try FfiConverterOptionBool.read(from: &buf), subscriptionIdentifiersAvailable: try FfiConverterOptionBool.read(from: &buf), sharedSubscriptionAvailable: try FfiConverterOptionBool.read(from: &buf), maximumPacketSize: try FfiConverterOptionUInt32.read(from: &buf)
        )
        
        case 9: return .pubRecReceived(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 10: return .pubRelReceived(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 11: return .pubCompReceived(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 12: return .pingResponseReceived
        
        case 13: return .publishSent(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 14: return .subscribeSent(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 15: return .unsubscribeSent(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 16: return .publishAckSent(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 17: return .pubRecSent(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 18: return .pubCompSent(packetId: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 19: return .pingSent
        
        case 20: return .disconnectSent
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConnectionEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connected:
            writeInt(&buf, Int32(1))
        
        
        case let .disconnected(reason,reasonCode):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            FfiConverterOptionString.write(reasonCode, into: &buf)
            
        
        case let .messageReceived(message):
            writeInt(&buf, Int32(3))
            FfiConverterTypeMqttMessage.write(message, into: &buf)
            
        
        case let .publishAck(packetId):
            writeInt(&buf, Int32(4))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .error(error):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(error, into: &buf)
            
        
        case let .subscribeAck(packetId,returnCodes,reasonCodesDetail):
            writeInt(&buf, Int32(6))
            FfiConverterUInt16.write(packetId, into: &buf)
            FfiConverterString.write(returnCodes, into: &buf)
            FfiConverterOptionString.write(reasonCodesDetail, into: &buf)
            
        
        case let .unsubscribeAck(packetId):
            writeInt(&buf, Int32(7))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .connAckDetails(sessionPresent,returnCode,reasonString,assignedClientId,serverKeepAlive,maximumQos,retainAvailable,wildcardSubscriptionAvailable,subscriptionIdentifiersAvailable,sharedSubscriptionAvailable,maximumPacketSize):
            writeInt(&buf, Int32(8))
            FfiConverterBool.write(sessionPresent, into: &buf)
            FfiConverterString.write(returnCode, into: &buf)
            FfiConverterOptionString.write(reasonString, into: &buf)
            FfiConverterOptionString.write(assignedClientId, into: &buf)
            FfiConverterOptionUInt16.write(serverKeepAlive, into: &buf)
            FfiConverterOptionUInt8.write(maximumQos, into: &buf)
            FfiConverterOptionBool.write(retainAvailable, into: &buf)
            FfiConverterOptionBool.write(wildcardSubscriptionAvailable, into: &buf)
            FfiConverterOptionBool.write(subscriptionIdentifiersAvailable, into: &buf)
            FfiConverterOptionBool.write(sharedSubscriptionAvailable, into: &buf)
            FfiConverterOptionUInt32.write(maximumPacketSize, into: &buf)
            
        
        case let .pubRecReceived(packetId):
            writeInt(&buf, Int32(9))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .pubRelReceived(packetId):
            writeInt(&buf, Int32(10))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .pubCompReceived(packetId):
            writeInt(&buf, Int32(11))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case .pingResponseReceived:
            writeInt(&buf, Int32(12))
        
        
        case let .publishSent(packetId):
            writeInt(&buf, Int32(13))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .subscribeSent(packetId):
            writeInt(&buf, Int32(14))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .unsubscribeSent(packetId):
            writeInt(&buf, Int32(15))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .publishAckSent(packetId):
            writeInt(&buf, Int32(16))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .pubRecSent(packetId):
            writeInt(&buf, Int32(17))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case let .pubCompSent(packetId):
            writeInt(&buf, Int32(18))
            FfiConverterUInt16.write(packetId, into: &buf)
            
        
        case .pingSent:
            writeInt(&buf, Int32(19))
        
        
        case .disconnectSent:
            writeInt(&buf, Int32(20))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionEvent_lift(_ buf: RustBuffer) throws -> ConnectionEvent {
    return try FfiConverterTypeConnectionEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionEvent_lower(_ value: ConnectionEvent) -> RustBuffer {
    return FfiConverterTypeConnectionEvent.lower(value)
}



extension ConnectionEvent: Equatable, Hashable {}




public enum MqttError {

    
    
    case ConnectionFailed(String
    )
    case NotConnected
    case InvalidConfig(String
    )
    case TlsError(String
    )
    case InternalError(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttError: FfiConverterRustBuffer {
    typealias SwiftType = MqttError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ConnectionFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotConnected
        case 3: return .InvalidConfig(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .TlsError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .InternalError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MqttError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ConnectionFailed(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .NotConnected:
            writeInt(&buf, Int32(2))
        
        
        case let .InvalidConfig(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .TlsError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InternalError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension MqttError: Equatable, Hashable {}

extension MqttError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MqttVersion {
    
    case v311
    case v5
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttVersion: FfiConverterRustBuffer {
    typealias SwiftType = MqttVersion

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttVersion {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .v311
        
        case 2: return .v5
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MqttVersion, into buf: inout [UInt8]) {
        switch value {
        
        
        case .v311:
            writeInt(&buf, Int32(1))
        
        
        case .v5:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttVersion_lift(_ buf: RustBuffer) throws -> MqttVersion {
    return try FfiConverterTypeMqttVersion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttVersion_lower(_ value: MqttVersion) -> RustBuffer {
    return FfiConverterTypeMqttVersion.lower(value)
}



extension MqttVersion: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum QosLevel {
    
    case atMostOnce
    case atLeastOnce
    case exactlyOnce
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQosLevel: FfiConverterRustBuffer {
    typealias SwiftType = QosLevel

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QosLevel {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .atMostOnce
        
        case 2: return .atLeastOnce
        
        case 3: return .exactlyOnce
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: QosLevel, into buf: inout [UInt8]) {
        switch value {
        
        
        case .atMostOnce:
            writeInt(&buf, Int32(1))
        
        
        case .atLeastOnce:
            writeInt(&buf, Int32(2))
        
        
        case .exactlyOnce:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQosLevel_lift(_ buf: RustBuffer) throws -> QosLevel {
    return try FfiConverterTypeQosLevel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQosLevel_lower(_ value: QosLevel) -> RustBuffer {
    return FfiConverterTypeQosLevel.lower(value)
}



extension QosLevel: Equatable, Hashable {}






public protocol MqttEventHandler : AnyObject {
    
    func onEvent(event: ConnectionEvent) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceMqttEventHandler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceMqttEventHandler = UniffiVTableCallbackInterfaceMqttEventHandler(
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMqttEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeConnectionEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceMqttEventHandler.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface MqttEventHandler: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitMqttEventHandler() {
    uniffi_mqtee_core_fn_init_callback_vtable_mqtteventhandler(&UniffiCallbackInterfaceMqttEventHandler.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceMqttEventHandler {
    fileprivate static var handleMap = UniffiHandleMap<MqttEventHandler>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceMqttEventHandler : FfiConverter {
    typealias SwiftType = MqttEventHandler
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeLastWillConfig: FfiConverterRustBuffer {
    typealias SwiftType = LastWillConfig?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeLastWillConfig.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeLastWillConfig.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSubscriptionRequest: FfiConverterRustBuffer {
    typealias SwiftType = [SubscriptionRequest]

    public static func write(_ value: [SubscriptionRequest], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSubscriptionRequest.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SubscriptionRequest] {
        let len: Int32 = try readInt(&buf)
        var seq = [SubscriptionRequest]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSubscriptionRequest.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUserProperty: FfiConverterRustBuffer {
    typealias SwiftType = [UserProperty]

    public static func write(_ value: [UserProperty], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUserProperty.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UserProperty] {
        let len: Int32 = try readInt(&buf)
        var seq = [UserProperty]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUserProperty.read(from: &buf))
        }
        return seq
    }
}
public func initLogging() {try! rustCall() {
    uniffi_mqtee_core_fn_func_init_logging($0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_mqtee_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_mqtee_core_checksum_func_init_logging() != 53613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqttclient_connect() != 9689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqttclient_disconnect() != 27825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqttclient_is_connected() != 49865) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqttclient_publish() != 62394) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqttclient_subscribe() != 36192) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqttclient_unsubscribe() != 53685) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_constructor_mqttclient_new() != 56321) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mqtee_core_checksum_method_mqtteventhandler_on_event() != 61249) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitMqttEventHandler()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all